from torchvision import models
from torchvision.models.resnet import *
from torchvision.models.vgg import *
from torchvision.models.squeezenet import *
from torchvision.models.densenet import *
from torchvision.models.mobilenet import mobilenet_v2
from torchvision.models.inception import *
from torchvision.models.alexnet import *
from torchvision.models.shufflenetv2 import *
from .resnet_mtl import *
from .alexnet_mtl import *
from .densenet_mtl import *
from .vgg_mtl import *